config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :events, only: [ :index, :show, :new, :create ] do
    resources :participations, only: [:new, :create]
    collection do
      get 'select', to: "events#select"
    end
    resources :users, only: [ :show ]
      collection do
        get 'my_events', to: "events#my_events"
      end
  end

  resources :users, only: [:show, :edit, :update] do
    resources :participations, only: [:index, :edit, :update, :show]
  end

mount Attachinary::Engine => "/attachinary"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
  class Event < ApplicationRecord
  geocoded_by :address
  after_validation :geocode, if: :address_changed?
  belongs_to :user
  has_many :participations, dependent: :destroy

  has_attachment :photo
  validates :title, :address, :description, :start_at, presence: true
end

app/models/participation.rb
class Participation < ApplicationRecord
  belongs_to :user
  belongs_to :event
  validates :rating, :numericality => {:only_integer => true, allow_nil: true}

  scope :upcoming, -> { joins(:event).where("events.start_at > ?", Time.now) }
  scope :past,     -> { joins(:event).where("events.start_at < ?", Time.now) }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :events, dependent: :destroy
  has_many :participations, dependent: :destroy
  validates :name, presence: true, uniqueness: true
  validates :sex, presence: true
  has_attachment :photo
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :sex, :age])
    # same as params.require(:user).permit(:first_name, :last_name)

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name, :sex, :age, :photo])
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController

  def index
    @near_events = Event.near(params[:search][:address], 20).where("start_at > ?", DateTime.now)


    if search_params[:sex].present? && search_params[:address].present?
      @events = Event.all.select do |event|
        @near_events.include?(event) && event.user.sex == search_params[:sex]
      end

    elsif !search_params[:address].present? && search_params[:sex].present?
      @events = Event.all.select do |event|
        event.user.sex == search_params[:sex]
      end

    elsif !search_params[:sex].present? && search_params[:address].present?
      @events = Event.all.select do |event|
        @near_events.include?(event)
      end

    else
      @events = Event.all
    end


    @hash = Gmaps4rails.build_markers(@events) do |event, marker|
      marker.lat event.latitude
      marker.lng event.longitude
    end

  end

  def my_events
    @my_events = Event.all.select do |event|
      event.user == current_user
    end
  end


  def show
    @event = Event.find(params[:id])
    @participation = Participation.new
  end

  def new
    @event = Event.new
  end

  def create
    @event = Event.new(event_params)
    @event.user = current_user
    if @event.save
      redirect_to event_path(@event)
    else
      render :new
    end
  end

  private

  def event_params
    params.require(:event).permit(:title, :address, :description, :start_at)
  end

  def search_params
    params.require(:search).permit(:sex, :address)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home
  end
end

app/controllers/participations_controller.rb
class ParticipationsController < ApplicationController

  before_action :set_event, only: [:new, :create]
  before_action :set_participation, only: [:edit, :update, :destroy, :show]
  def new
    @participation = Participation.new
  end

  def create
    @participation = Participation.new
    @participation.user = current_user
    @participation.event = @event
    if @participation.save
      redirect_to user_participations_path(current_user)
    else
      render event_path(@event)
    end
  end

  def edit
  end

  def update
    if @participation.update(participations_params)
      redirect_to user_participations_path(current_user)
    else
      render :edit
    end
  end

  def destroy
    @participation.destroy
    redirect_to @user
  end

  def index
    @participations = Participation.all
  end

  def show
  end

  private

  def set_event
    @event = Event.find(params[:event_id])
  end

  def participations_params
    params.require(:participation).permit(:rating, :review)
  end

  def set_participation
    @participation = Participation.find(params[:id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :destroy, :edit, :update]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to @user
    else
      render :new
    end
  end

  def show
  end

  def destroy
    @user.destroy
  end

  def edit
  end

  def update
    if @user.update(user_params)
      redirect_to @user
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :sex, :photo)
  end

  def set_user
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
   @devise_mapping ||= Devise.mappings[:user]
 end
end

app/views/events/_cards.html.erb
<div class="container">
  <div class="row">
    <% @events.each do |event| %>
      <div class="col-xs-12 col-sm-4">
        <div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('https://images.unsplash.com/photo-1491707202941-6395f060840f?dpr=2&auto=format&fit=crop&w=1500&h=1125&q=80&cs=tinysrgb&crop=');">
        <div class="card-category"><%= event.title %></div>
        <div class="card-description">
          <h2><i class="fa fa-map-marker" aria-hidden="true"></i><%= event.address %></h2>
          <h2><i class="fa fa-calendar" aria-hidden="true"></i><%= event.start_at %></h2>
        </div>
          <img class="card-user" src="https://kitt.lewagon.com/placeholder/users/tgenai">
          <a class="card-link" href="#" ></a>
        </div>
      </div>
    <%end%>
  </div>
</div>

app/views/events/index.html.erb
<div class="all-content">
  <div class="row">
    <div class="col-sm-8">
      <div class="main-content">
        <div class=" margin-zero row">
          <div class="search-bar text-center">
            <%= simple_form_for :search, :html => { role: 'form', class: 'form-inline' }, url: events_path, method: :get do |f|  %>
              <%= f.input :sex, :label => false, collection:['⚣ Gay', '⚢ Lesbian', '⚤ Straight'], input_html: { value: params[:search][:sex] } %>
              <%= f.input :address, placeholder: "Paris", label: false, input_html: { value: params[:search][:address] } %>
              <% if user_signed_in? %>
              <%= f.button :submit, "Let's swing" %>
              <% else %>
              <button type="button" class="btn btn-danger-home" data-toggle="modal" data-target="#myModal">
                Let's swing
              </button>
              <% end %>
            <% end %>
          </div>

          <% @events.each do |event| %>
            <div class="col-xs-12 col-sm-6 col-md-4">
              <% if event.start_at > Time.now %>
              <div class="card">
                <% if event.photo? %>
                  <div class="card-body" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('<%= cl_image_path event.photo.path%>');">
                <% else %>
                <div class="card-body" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('https://images.unsplash.com/photo-1491707202941-6395f060840f?dpr=2&auto=format&fit=crop&w=1500&h=1125&q=80&cs=tinysrgb&crop=');">
                <% end %>
                  <div class="card-category"><%= event.user.name  %></div>
                    <div class="card-description">
                      <h2><%= event.title %></h2>
                      <p><i class="fa fa-map-marker" aria-hidden="true"></i> <%= event.address %></p>
                    </div>
                  <% if event.user.photo? %>
                    <img class="card-user" src="<%= cl_image_path event.user.photo.path%>">
                  <% end %>
                  <%= link_to "", event_path(event), class: "card-link"  %>
                </div>
                <div class="card-footer">
                  <p><i class="fa fa-calendar" aria-hidden="true"></i> <%= event.start_at.strftime("Scheduled on %d/%m/%Y") %></p>
                </div>
              </div>
              <%end%>
            </div>
          <%end%>
        </div>
      </div>
    </div>
    <div class="col-sm-4">
      <div id="map" style="width: 100%; height: 600px;"></div>
    </div>
  </div>
</div>

<%= content_for(:after_js) do %>
  <script>
    $(document).ready(function() {
      var handler = Gmaps.build('Google');
      handler.buildMap({ internal: { id: 'map' } }, function() {
        markers = handler.addMarkers(<%= raw @hash.to_json %>);
        handler.bounds.extendWith(markers);
        handler.fitMapToBounds();
        if (markers.length == 0) {
          handler.getMap().setZoom(2);
        } else if (markers.length == 1) {
          handler.getMap().setZoom(14);
        }
      });
    });
  </script>
<% end %>

app/views/events/my_events.html.erb
<div id="events">

  <div class="tabs text-center">
    <%= link_to "Profile", user_path(current_user), class: "tab" %>
    <%= link_to "My swings", "#", class: "tab active" %>
    <%= link_to "My participations", user_participations_path(current_user), class: "tab" %>
  </div>


  <% @my_events.each do |event| %>
    <div class="event">
      <div class="details">
        <%= event.start_at %>
      </div>
      <div class="title">
        <%= event.title %>
      </div>
      <div class="description">
        <%= event.description %>
      </div>
    </div>
  <% end %>
  <div class="swing">
    <%= link_to "Create a Swing", new_event_path, class: "btn btn-primary cta" %>
  </div>
</div>

app/views/events/new.html.erb
<div class="container">
<h1 class="text-center">Create a Swing</h1>
  <div class="row">
    <div class="col-md-4 col-md-offset-4">
    <%= simple_form_for @event do |f|%>
      <%= f.input :title, placeholder: 'Soirée cuir-moustache...' %>
      <%= f.input :start_at, value: Time.now%>
      <%= f.input :description, placeholder: 'Loulou & Coco, 28 et 34 ans vous accueillent pour une soirée chaude!'  %>
      <%= f.input :address %>
      <%= f.input :photo, as: :attachinary, class: "image-field"  %>
      <%= f.button :submit, class: "btn btn-primary" %>
    <% end %>
    </div>
  </div>
</div>

app/views/events/show.html.erb
<div class="event-show">

  <div class="banner" style="background-image: linear-gradient(-225deg, rgba(5,6,32,0.2) 0%, rgba(5,6,32,0.8) 50%), url(<%= image_url('fresque.jpg') %>)"; >
    <div class="banner-content">

  <aside class="profile-card">
    <header>
      <!-- here’s the avatar -->

      <!-- the username -->
      <h1>
        <%= @event.user.name %>
      </h1>

      <!-- and role or location -->
      <h2>
        <%= @event.title %>
      </h2>
      <h3> Location : <%= @event.address %></h4>

    </header>

    <div class="profile-bio">

      <h4>
        <%= @event.description %>
      </h4>

    </div>

    <!-- some social links to show off -->
  <div class="participate">
        <%= simple_form_for [@event, @participation] do |f| %>
          <%= f.button :submit, value: "Confirm Participation", class: "btn btn-primary cta"  %>
            <% end %>
          </div>

  </aside>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Let's Swing!</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <link href="https://fonts.googleapis.com/css?family=Roboto:300,400" rel="stylesheet">
    <%= stylesheet_link_tag 'application', media: 'all' %>
  </head>
  <body>

    <%= render 'shared/navbar' unless yield(:navbar_home) == "yes" %>
    <%= render 'components/navbar_home' if yield(:navbar_home) == "yes" %>

    <%= render 'shared/flashes' %>
    <%= yield %>

    <%= javascript_include_tag "https://maps.google.com/maps/api/js?libraries=places&key=#{ENV['GOOGLE_API_SERVER_KEY']}" %>
    <%= javascript_include_tag "https://cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/markerclusterer/src/markerclusterer_compiled.js" %>
    <%= javascript_include_tag "https://cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/infobox/src/infobox_packed.js" %>

    <%= javascript_include_tag 'application' %>


    <%= yield(:after_js) %> <!-- I am calling after_js from my home -->

    <%= cloudinary_js_config %>

  </body>
</html>

app/views/pages/_banner.html.erb
<div class="banner-js">
<script type="text/javascript">
  var TxtType = function(el, toRotate, period) {
        this.toRotate = toRotate;
        this.el = el;
        this.loopNum = 0;
        this.period = parseInt(period, 10) || 2000;
        this.txt = '';
        this.tick();
        this.isDeleting = false;
    };
    TxtType.prototype.tick = function() {
        var i = this.loopNum % this.toRotate.length;
        var fullTxt = this.toRotate[i];
        if (this.isDeleting) {
        this.txt = fullTxt.substring(0, this.txt.length - 1);
        } else {
        this.txt = fullTxt.substring(0, this.txt.length + 1);
        }
        this.el.innerHTML = '<span class="wrap">'+this.txt+'</span>';
        var that = this;
        var delta = 200 - Math.random() * 100;
        if (this.isDeleting) { delta /= 2; }
        if (!this.isDeleting && this.txt === fullTxt) {
        delta = this.period;
        this.isDeleting = true;
        } else if (this.isDeleting && this.txt === '') {
        this.isDeleting = false;
        this.loopNum++;
        delta = 500;
        }
        setTimeout(function() {
        that.tick();
        }, delta);
    };
    window.onload = function() {
        var elements = document.getElementsByClassName('typewrite');
        for (var i=0; i<elements.length; i++) {
            var toRotate = elements[i].getAttribute('data-type');
            var period = elements[i].getAttribute('data-period');
            if (toRotate) {
              new TxtType(elements[i], JSON.parse(toRotate), period);
            }
        }
        // INJECT CSS
        var css = document.createElement("style");
        css.type = "text/css";
        css.innerHTML = ".typewrite > .wrap { border-right: 0.08em solid #fff}";
        document.body.appendChild(css);
    };
</script>
</div>

app/views/pages/home.html.erb
<% content_for(:navbar_home, "yes") %>

<div class="banner" style="background-image: linear-gradient(-225deg, rgba(5,6,32,0.2) 0%, rgba(5,6,32,0.8) 50%), url(<%= image_url('fresque.jpg') %>)";>
  <div class="banner-content">
      <h1 href="" class="typewrite" data-period="2000" data-type='[ "Hi, I am looking for Fun.", "I am Open-minded.", "... and I love Sex." ]'>
        <span class="wrap"></span>
      </h1>


    <%= simple_form_for :search, :html => { role: 'form', class: 'form-inline' }, url: events_path, method: :get do |f|  %>
      <%= f.input :sex, prompt: "I am horny for", :label => false, collection:['⚣ Gay', '⚢ Lesbian', '⚤ Straight'] %>
      <%= f.input :address, placeholder: "Paris", label: false %>
      <% if user_signed_in? %>
        <%= f.button :submit, "Let's swing", class: "search-btn" %>
      <% else %>
        <button type="button" class="btn btn-default search-btn" data-toggle="modal" data-target="#myModal">
          Let's swing
        </button>
      <% end %>
    <% end %>

  </div>
</div>

<!-- Button trigger modal -->

  <!-- Modal -->
  <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
          <h4 class="modal-title" id="myModalLabel">Match me to other Swingers</h4>
        </div>
        <div class="modal-body">
         <h2>Sign up</h2>

         <%= simple_form_for(resource, as: resource_name, url: registration_path(resource_name)) do |f| %>
         <%= f.error_notification %>

         <div class="form-inputs">
          <%= f.input :name, required: true %>
          <%= f.input :sex, label: 'My couple is', required: true, :collection => ['Man & Woman', 'Man & Man', 'Woman & Woman'] %>
          <%= f.input :age, required: true %>
          <%= f.input :email, required: true, autofocus: true %>
          <%= f.input :password, required: true, hint: ("#{@minimum_password_length} characters minimum" if @minimum_password_length) %>
          <%= f.input :password_confirmation, required: true %>
        </div>

        <div class="form-actions">
          <%= f.button :submit, "Sign up" %>
        </div>
        <% end %>

        <%= render "devise/shared/links" %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
      </div>
    </div>
  </div>

<div class="fullwidth-content">
  <div class="row">
    <div class="col-md-4">
      <div class="info-content text-center">
        <h3 class="num">
          <p><span><i class="fa fa-venus-mars" aria-hidden="true"></i></span></p>
        </h3>
        <h4>Choose Orientation</h4>
        <p>
          We enable all types of couples to match, you choose the orientation that you feel like meeting!
        </p>
      </div>
    </div>
    <div class="col-md-4">
      <div class="info-content text-center">
        <h3 class="num">
          <p><span><i class="fa fa-globe" aria-hidden="true"></i></span></p>
        </h3>
        <h4>Choose Location</h4>
        <p>
          The world is your oyster! Literally. We connect swingers all over the world.
        </p>
      </div>
    </div>
    <div class="col-md-4">
      <div class="info-content text-center">
        <h3 class="num">
          <p><span><i class="fa fa-heart-o" aria-hidden="true"></i></span></p>
        </h3>
        <h4>Book Swing-Event</h4>
        <p>
          Found your happiness? Book in one click!
        </p>
      </div>
    </div>
  </div>
</div>


<div class="container">
  <div class="row">
    <div class="col-md-12">
      <div class="carousel slide" data-ride="carousel" id="quote-carousel">
        <!-- Carousel Slides / Quotes -->
        <div class="carousel-inner text-center">
          <!-- Quote 1 -->
          <div class="item active">
            <blockquote>
              <div class="row">
                <div class="col-sm-8 col-sm-offset-2">
                <p>After many years with my booboo, our 'date nights' started lacking creativity.  I am officially a swinger, and I love it!</p>
                <!-- We've always been quite curious about going outside our comfortzone sexually to spice up our relationship. So when we went on a long week-end away to London from our hometown we thought it was the perfect moment to try it out! The encounter was spot on. -->
                  <small>Aston</small>
                </div>
              </div>
            </blockquote>
          </div>
          <!-- Quote 2 -->
          <div class="item">
            <blockquote>
              <div class="row">
                <div class="col-sm-8 col-sm-offset-2">
                  <p>I tend to be late to many things, but I can assure you I didn't 'come' late this time! </p>
                  <small>Cyril</small>
                </div>
              </div>
            </blockquote>
          </div>
          <!-- Quote 3 -->
          <div class="item">
            <blockquote>
              <div class="row">
                <div class="col-sm-8 col-sm-offset-2">
                  <p>Ma femme Tchouchou et moi avons beaucoup apprécié ce moment de partage. Nous éspèrons revoir Jérome et Arnaud très vite. </p>
                  <small>Maxou</small>
                </div>
              </div>
            </blockquote>
          </div>
        <!-- Quote 4 -->
          <div class="item">
            <blockquote>
              <div class="row">
                <div class="col-sm-8 col-sm-offset-2">
                  <p>Je suis très serieux, mais au fond de moi je suis un petit coquin et un artiste! Let's Swing m'a permis de m'épanouir dans les rencontres échangistes, tout en sécurité et seriosité.</p>
                  <small>Bertrand</small>
                </div>
              </div>
            </blockquote>
          </div>
        </div>



        <!-- Bottom Carousel Indicators -->
        <ol class="carousel-indicators">
          <li data-target="#quote-carousel" data-slide-to="0" class="active"><img class="img-responsive " src="https://kitt.lewagon.com/placeholder/users/tgenai">
          </li>
          <li data-target="#quote-carousel" data-slide-to="1"><img class="img-responsive" src="https://avatars3.githubusercontent.com/u/28042850?v=4" alt="">
          </li>
          <li data-target="#quote-carousel" data-slide-to="2"><img class="img-responsive" src="https://avatars1.githubusercontent.com/u/20045463?v=4" alt="">
          </li>
          <li data-target="#quote-carousel" data-slide-to="2"><img class="img-responsive" src="https://farm3.static.flickr.com/2651/5769205374_f492981753_b.jpg" alt="">
          </li>
        </ol>


        <!-- Carousel Buttons Next/Prev -->
        <a data-slide="prev" href="#quote-carousel" class="left carousel-control"><i class="fa fa-chevron-left"></i></a>
        <a data-slide="next" href="#quote-carousel" class="right carousel-control"><i class="fa fa-chevron-right"></i></a>
      </div>
    </div>
  </div>
</div>





  <% content_for :after_js do %>
    <%= render 'banner' %>
<% end %>

app/views/participations/index.html.erb
<div class="container">
  <div class="tabs text-center">
    <%= link_to "Profile", user_path(current_user), class: "tab" %>
    <%= link_to "My swings", my_events_events_path, class: "tab" %>
    <%= link_to "My participations", user_participations_path(current_user), class: "tab active" %>
  </div>


  <div class="row">

    <div class="col-xs-6">
      <h2>Upcoming</h2>
      <div class="row">
        <% @participations.upcoming.each do |participation| %>
          <div class="col-xs-6">
            <%= render "participations/participation", participation: participation %>
          </div>
        <% end %>
      </div>
    </div>

    <div class="col-xs-6">
      <h2>Past</h2>
      <div class="row">
        <% @participations.past.each do |participation| %>
          <div class="col-xs-6">
            <%= render "participations/participation", participation: participation %>
          </div>
        <% end %>
      </div>
    </div>

  </div>
</div>

app/views/participations/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-6 col-sm-offset-3">
        <%= simple_form_for [@event, @participation] do |f| %>
          <%= f.button :submit, value: "Participate", class: "btn btn-primary"  %>
        <% end %>
    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
    <%= image_tag "EYE.png" %>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <% if user_signed_in? %>

      <!-- Links when logged in -->
      <%= link_to "Create a swing", new_event_path, class: "navbar-wagon-item navbar-wagon-link" %>

      <!-- Avatar with dropdown menu -->
      <div class="navbar-wagon-item">
        <div class="dropdown">
          <% if !current_user.photo? %>
            <% photo_url = "avatar-placeholder.png" %>
          <% else %>
            <% photo_url = current_user.photo.path %>
          <% end %>
          <%= cl_image_tag(photo_url, width: 40, height: 40, crop: :fill,  class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown") %>

          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li>
              <%= link_to user_path(current_user) do %>
                <i class="fa fa-user"></i> <%= t(".profile", default: "Profile") %>
              <% end %>
            </li>
            <li>
              <%= link_to "#" do %>
                <i class="fa fa-home"></i>  <%= t(".profile", default: "My swings") %>
              <% end %>
            </li>
            <li>
              <%= link_to user_participations_path(current_user) do %>
                <i class="fa fa-rocket"></i>  <%= t(".profile", default: "My participations") %>
              <% end %>
            </li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
              <% end %>
            </li>
          </ul>

        </div>
      </div>
    <% else %>
      <!-- Login link (when logged out) -->
      <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>
      <%= link_to t(".sign_up", default: "Sign Up"), new_user_registration_path, class: "navbar-home-item navbar-home-link" %>
    <% end %>
  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><a href="#">Some mobile link</a></li>
        <li><a href="#">Other one</a></li>
        <li><a href="#">Other one</a></li>
      </ul>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="container">

    <div class="tabs text-center">
      <%= link_to "Profile", "#", class: "tab active" %>
      <%= link_to "My swings", my_events_events_path, class: "tab" %>

      <%= link_to "My participations", user_participations_path(current_user), class: "tab" %>
    </div>

    <div class="container">
      <div class="row tab-content" id="profile">
        <div class="col-xs-12 col-sm-4 border-right">
          <% if !current_user.photo? %>
            <div class="text-center">
              <%= image_tag("couple-placeholder.png", width: 200, height: 200, crop: :fill) %>
            </div>
          <% else %>
            <div class="text-center">
              <%= cl_image_tag current_user.photo.path, width: 200, height: 200, radius: :max, crop: :fill,  gravity: :face %>
            </div>
          <% end %>
        </div>
        <div class="col-xs-12 col-sm-8">
          <%= simple_form_for current_user do |f| %>
            <%= f.input :name, disabled: true, label: "Couple Name" %>
            <%= f.input :sex, disabled: true, collection: ["Man & Woman", "Man & Man", "Woman & Woman"], label: "Couple Type" %>
          <% end %>
          <i class="fa fa-pencil" aria-hidden="true"></i><%= link_to " edit my profile", edit_user_path(current_user) %>
          <h2 class="review-title">Reviews</h2>

          <div class="review">
            <% current_user.events.each do |event| %>
              <% event.participations.each do |participation| %>
              <% if participation.review %>
                <% if !participation.user.photo? %>
                  <%= cl_image_tag "avatar-placeholder.png", width: 60, height: 60, crop: :fill %>
                <% else %>
                  <%= cl_image_tag participation.user.photo.path, width: 60, height: 60, radius: :max, crop: :fill,  gravity: :face %>
                <% end %>
                  <div class="review-details">
                  <%  full = participation.rating.to_i %>
                  <span><%= "✭" * full + "✩" * (10 - full) %></span>
                  <p><%= participation.review %></p>
                  </div>
                <% end %>
              <% end %>
            <% end %>
          </div>

        </div>
      </div>
  </div>
</div>